### ISSUE TITLE
We should probably do #1 together

### ISSUE THREAD

**Issue by klvs** [klvs/CS101#1]
The rest seems like charting and such.

**Comment by terminull** [comment]
#1 is basically just citing from the book right? Since I will not probably be here this weekend, do we want to attempt the homework separately and then regroup on Monday? This assignment seems easy enough that not working together at first will not be an issue.

**Comment by klvs** [comment]
Sounds good to me. Give me the heads up before you start working so we can maybe "divide and conquer" on appropriate parts.

**Comment by klvs** [comment]
@terminull Hey, I'm going to do the insertion sort portion of #1 since you did the merge sort one.
